server:
    port: 9999

spring:
    application:
        name: auth-server
    cloud:
        nacos:
            server-addr: nacos-server:8848
            discovery:
                enabled: true
                namespace: dev
                group: DEFAULT_GROUP
                register-enabled: true
            config:
                enabled: true
                namespace: dev
                group: DEFAULT_GROUP
                file-extension: yaml
    redis:
        host: redis-server
        port: 6380
        password: 20021221
    datasource:
        url: jdbc:mysql://mysql-server:3307/coin-exchange?useSSL=false&serverTimezone=GMT%2B8
        username: root
        password: 20021221
        driver-class-name: com.mysql.cj.jdbc.Driver

# 添加日志配置，方便排查问题
logging:
    level:
        com.alibaba.nacos: DEBUG
        com.wc: DEBUG